# Generated by Django 3.1.1 on 2020-12-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0026_auto_20201111_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='data_created',
            new_name='dataCreated',
        ),
        migrations.RenameField(
            model_name='magazine',
            old_name='date_created',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_created',
            new_name='dateCreated',
        ),
    ]
